-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohVector31 = game.Players.coldheck.Character.HumanoidRootPart.Position
local ohVector32 = game.Players.coldheck.Character.HumanoidRootPart.Position
local ohBrickColor3 = BrickColor.New("Institutional white")

game:GetService("ReplicatedStorage").StrongPunch:FireServer(ohVector31, ohVector32, ohBrickColor3)
